# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: View directories
      run: |
        DIR=$(cwd)
        echo $DIR
        ls -lah
    - name: Install dependencies
      run: |
        cd ..
        git clone https://github.com/ultralytics/ultralytics.git
        cd $DIR
        python -m pip install --upgrade pip
        pip install flake8 pytest 
        # pip install -e ../ultralytics
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Check docs location
      run: ls -lah && cd ultralytics && ls -lah
    - name: Test with pytest
      run: |
        pytest
